// apps/meet/src/App.svelte
<script lang="ts">
  import Lobby from "./Lobby.svelte";
  import Room from "./Room.svelte";

  let page = $state<"lobby" | "room">("lobby");
  let roomId = $state("");
  let localStream = $state<MediaStream | null>(null);

  function handleJoin(id: string) {
    roomId = id;
    page = "room";
  }

  function handleLeave() {
    page = "lobby";
    localStream = null;
  }
</script>

<main class="container-fluid">
  {#if page === "lobby" || !localStream}
    <Lobby bind:localStream onJoin={handleJoin} />
  {:else}
    <Room {localStream} {roomId} onLeave={handleLeave} />
  {/if}
</main>

<style>
  :global(body > main) {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
  }
</style>

// apps/meet/app/page.tsx
"use client";

import { useState } from "react";
import { Lobby } from "../components/Lobby";
import { Room } from "../components/Room";

export default function Home() {
  const [roomId, setRoomId] = useState("");
  const [localStream, setLocalStream] = useState<MediaStream | null>(null);
  const [page, setPage] = useState<"lobby" | "room">("lobby");

  const handleJoin = (id: string) => {
    setRoomId(id);
    setPage("room");
  };

  const handleLeave = () => {
    setPage("lobby");
    setLocalStream(null); // Reset stream on leave to force re-acquisition or just cleanup
  };

  if (page === "lobby" || !localStream) {
    return (
      <Lobby
        localStream={localStream}
        setLocalStream={setLocalStream}
        onJoin={handleJoin}
      />
    );
  }

  return <Room roomId={roomId} localStream={localStream} onLeave={handleLeave} />;
}
