// apps/meet/src/App.svelte
<script lang="ts">
  import { onDestroy } from "svelte";
  import {
    Participant,
    ParticipantEvent,
    binder,
    RemoteTrack,
  } from "./lib/svelte";

  const participant = new Participant({ videoSlots: 16, audioSlots: 3 });

  let connectionState = $state(participant.state);
  let participantId = $state<string>();
  let tracks = $state<RemoteTrack[]>([]);

  const cleanup = [
    participant.on(ParticipantEvent.State, (s) => (connectionState = s)),
    participant.on(ParticipantEvent.TrackAdded, ({ track }) =>
      tracks.push(track),
    ),
    participant.on(ParticipantEvent.TrackRemoved, ({ trackId }) => {
      tracks = tracks.filter((t) => t.id !== trackId);
    }),
  ];

  onDestroy(() => cleanup.forEach((off) => off()));

  const streamPromise = navigator.mediaDevices
    .getUserMedia({ video: { height: 720 }, audio: true })
    .then((stream) => {
      participant.publish(stream);
      return stream;
    });

  async function connect() {
    try {
      participantId = await participant.connect(
        "https://demo.pulsebeam.dev",
        "8hlofgn",
      );
    } catch (e) {
      console.error(e);
    }
  }
</script>

<main class="container">
  {#await streamPromise}
    <article aria-busy="true">Initializing Camera...</article>
  {:then localStream}
    <div class="grid">
      <article>
        <header><strong>Local ({participantId || "You"})</strong></header>
        <video srcObject={localStream} autoplay muted></video>
      </article>

      <article>
        <header>
          <strong>Status: {connectionState}</strong>
        </header>

        {#if connectionState === "connected"}
          <div class="video-grid">
            {#each tracks as track (track.id)}
              <div class="remote-video">
                <video use:binder={track} autoplay playsinline></video>
                <small>{track.participantId}</small>
              </div>
            {/each}
          </div>
        {:else if connectionState === "closed" || participant.error}
          <div class="headings">
            <h4 style="color: var(--pico-del-color)">Error</h4>
            <p>{participant.error || "Connection closed"}</p>
            <button onclick={connect} class="contrast">Retry</button>
          </div>
        {:else}
          <button
            onclick={connect}
            aria-busy={connectionState === "connecting"}
            disabled={connectionState === "connecting"}
          >
            {connectionState === "connecting" ? "Connecting..." : "Join Room"}
          </button>
        {/if}
      </article>
    </div>
  {:catch err}
    <article>
      <header style="color: var(--pico-del-color)">
        <strong>Camera Error</strong>
      </header>
      {err.message}
    </article>
  {/await}
</main>

<style>
  video {
    width: 100%;
    border-radius: var(--pico-border-radius);
    background: #000;
  }

  .video-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
    gap: 1rem;
  }
</style>

// libs/react/src/App.tsx
import { useState } from "react";
import { useParticipant, Video, Audio, type ParticipantConfig } from "./lib";

const APP_CONFIG: ParticipantConfig = {
  videoSlots: 16,
  audioSlots: 8,
};

export default function MeetingRoom() {
  const [roomId, setRoomId] = useState("demo-room");

  const client = useParticipant(APP_CONFIG);

  const handleJoin = async () => {
    let stream;
    try {
      stream = await navigator.mediaDevices.getUserMedia({
        video: true,
        audio: true,
      });
    } catch (err) {
      console.error("Failed to join:", err);
      return;
    }

    client.publish(stream);
    client.connect(roomId);
  };

  const handleLeave = () => {
    client.close();
  };

  return (
    <div style={{ padding: "20px", fontFamily: "sans-serif" }}>
      <h1>Pulsebeam Room: {roomId}</h1>

      <p>
        Status: <strong>{client.connectionState}</strong>
      </p>

      {client.connectionState !== "connected" ? (
        <button onClick={handleJoin}>Join Meeting</button>
      ) : (
        <button
          onClick={handleLeave}
          style={{ background: "red", color: "white" }}
        >
          Leave Meeting
        </button>
      )}

      <hr />

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
          gap: "10px",
        }}
      >
        {client.videoTracks.map((track) => (
          <div
            key={track.id}
            style={{
              border: "1px solid #ccc",
              borderRadius: "8px",
              overflow: "hidden",
            }}
          >
            <Video track={track} style={{ width: "100%", display: "block" }} />
            <p style={{ padding: "5px", margin: 0 }}>{track.participantId}</p>
          </div>
        ))}
      </div>

      {client.audioTracks.map((track) => (
        <Audio track={track} />
      ))}
    </div>
  );
}
